import type { CatalogEntry } from "../types";

export const RESOURCE_CATALOG: CatalogEntry[] = [
  // ── Search Engines ──
  {
    id: "google",
    name: "Google",
    url: "https://www.google.com",
    icon: "google",
    color: "#4285F4",
    category: "Search Engines",
  },
  {
    id: "bing",
    name: "Bing",
    url: "https://www.bing.com",
    icon: "microsoft-bing",
    color: "#008373",
    category: "Search Engines",
  },
  {
    id: "duckduckgo",
    name: "DuckDuckGo",
    url: "https://duckduckgo.com",
    icon: "duck",
    color: "#DE5833",
    category: "Search Engines",
  },
  {
    id: "brave-search",
    name: "Brave Search",
    url: "https://search.brave.com",
    icon: "shield-search",
    color: "#FB542B",
    category: "Search Engines",
  },
  {
    id: "yahoo",
    name: "Yahoo",
    url: "https://www.yahoo.com",
    icon: "yahoo",
    color: "#6001D2",
    category: "Search Engines",
  },

  // ── DNS Providers ──
  {
    id: "google-dns",
    name: "Google DNS",
    url: "https://dns.google",
    icon: "dns",
    color: "#4285F4",
    category: "DNS Providers",
  },
  {
    id: "cloudflare-dns",
    name: "Cloudflare DNS",
    url: "https://one.one.one.one",
    icon: "cloud-outline",
    color: "#F6821F",
    category: "DNS Providers",
  },
  {
    id: "adguard-dns",
    name: "AdGuard DNS",
    url: "https://adguard-dns.io",
    icon: "shield-check",
    color: "#68BC71",
    category: "DNS Providers",
  },
  {
    id: "opendns",
    name: "OpenDNS",
    url: "https://www.opendns.com",
    icon: "dns-outline",
    color: "#FFB400",
    category: "DNS Providers",
  },
  {
    id: "duckdns",
    name: "Duck DNS",
    url: "https://www.duckdns.org",
    icon: "duck",
    color: "#E8A735",
    category: "DNS Providers",
  },

  // ── Cloud & Hosting ──
  {
    id: "aws",
    name: "AWS",
    url: "https://aws.amazon.com",
    icon: "aws",
    color: "#FF9900",
    category: "Cloud & Hosting",
  },
  {
    id: "microsoft-azure",
    name: "Microsoft Azure",
    url: "https://azure.microsoft.com",
    icon: "microsoft-azure",
    color: "#0078D4",
    category: "Cloud & Hosting",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    url: "https://www.cloudflare.com",
    icon: "cloud",
    color: "#F6821F",
    category: "Cloud & Hosting",
  },
  {
    id: "vercel",
    name: "Vercel",
    url: "https://vercel.com",
    icon: "triangle",
    color: "#000000",
    category: "Cloud & Hosting",
  },
  {
    id: "ibm",
    name: "IBM Cloud",
    url: "https://www.ibm.com",
    icon: "server",
    color: "#0F62FE",
    category: "Cloud & Hosting",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    url: "https://www.digitalocean.com",
    icon: "water",
    color: "#0080FF",
    category: "Cloud & Hosting",
  },
  {
    id: "alibaba-cloud",
    name: "Alibaba Cloud",
    url: "https://www.alibabacloud.com",
    icon: "cloud-braces",
    color: "#FF6A00",
    category: "Cloud & Hosting",
  },
  {
    id: "flyio",
    name: "Fly.io",
    url: "https://fly.io",
    icon: "airplane",
    color: "#8B5CF6",
    category: "Cloud & Hosting",
  },
  {
    id: "render",
    name: "Render",
    url: "https://render.com",
    icon: "cube-outline",
    color: "#46E3B7",
    category: "Cloud & Hosting",
  },
  {
    id: "netlify",
    name: "Netlify",
    url: "https://www.netlify.com",
    icon: "web",
    color: "#00C7B7",
    category: "Cloud & Hosting",
  },

  // ── Dev Tools ──
  {
    id: "github",
    name: "GitHub",
    url: "https://github.com",
    icon: "github",
    color: "#24292F",
    category: "Dev Tools",
  },
  {
    id: "gitlab",
    name: "GitLab",
    url: "https://gitlab.com",
    icon: "git",
    color: "#FC6D26",
    category: "Dev Tools",
  },
  {
    id: "docker-hub",
    name: "Docker Hub",
    url: "https://hub.docker.com",
    icon: "docker",
    color: "#2496ED",
    category: "Dev Tools",
  },
  {
    id: "mdn-docs",
    name: "MDN Web Docs",
    url: "https://developer.mozilla.org",
    icon: "book-open-variant",
    color: "#000000",
    category: "Dev Tools",
  },
  {
    id: "sentry",
    name: "Sentry",
    url: "https://sentry.io",
    icon: "bug-outline",
    color: "#362D59",
    category: "Dev Tools",
  },
  {
    id: "grafana",
    name: "Grafana",
    url: "https://grafana.com",
    icon: "chart-line",
    color: "#F46800",
    category: "Dev Tools",
  },
  {
    id: "unreal-engine",
    name: "Unreal Engine",
    url: "https://www.unrealengine.com",
    icon: "gamepad-variant",
    color: "#313131",
    category: "Dev Tools",
  },
  {
    id: "unity-hub",
    name: "Unity Hub",
    url: "https://unity.com",
    icon: "unity",
    color: "#222C37",
    category: "Dev Tools",
  },

  // ── Databases & Backend ──
  {
    id: "supabase",
    name: "Supabase",
    url: "https://supabase.com",
    icon: "database",
    color: "#3ECF8E",
    category: "Databases & Backend",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    url: "https://www.mongodb.com",
    icon: "leaf",
    color: "#47A248",
    category: "Databases & Backend",
  },
  {
    id: "neondb",
    name: "Neon DB",
    url: "https://neon.tech",
    icon: "database-outline",
    color: "#00E599",
    category: "Databases & Backend",
  },
  {
    id: "redis",
    name: "Redis",
    url: "https://redis.io",
    icon: "database-cog",
    color: "#DC382D",
    category: "Databases & Backend",
  },

  // ── Auth & Payments ──
  {
    id: "clerk",
    name: "Clerk",
    url: "https://clerk.com",
    icon: "account-key",
    color: "#6C47FF",
    category: "Auth & Payments",
  },
  {
    id: "stripe",
    name: "Stripe",
    url: "https://stripe.com",
    icon: "credit-card-outline",
    color: "#635BFF",
    category: "Auth & Payments",
  },

  // ── Social Media ──
  {
    id: "facebook",
    name: "Facebook",
    url: "https://www.facebook.com",
    icon: "facebook",
    color: "#1877F2",
    category: "Social Media",
  },
  {
    id: "instagram",
    name: "Instagram",
    url: "https://www.instagram.com",
    icon: "instagram",
    color: "#E4405F",
    category: "Social Media",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    url: "https://www.linkedin.com",
    icon: "linkedin",
    color: "#0A66C2",
    category: "Social Media",
  },
  {
    id: "x-com",
    name: "X.com",
    url: "https://x.com",
    icon: "twitter",
    color: "#000000",
    category: "Social Media",
  },
  {
    id: "tiktok",
    name: "TikTok",
    url: "https://www.tiktok.com",
    icon: "music-note",
    color: "#010101",
    category: "Social Media",
  },

  // ── Messaging ──
  {
    id: "telegram",
    name: "Telegram",
    url: "https://web.telegram.org",
    icon: "send",
    color: "#26A5E4",
    category: "Messaging",
  },
  {
    id: "discord",
    name: "Discord",
    url: "https://discord.com",
    icon: "chat",
    color: "#5865F2",
    category: "Messaging",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    url: "https://web.whatsapp.com",
    icon: "whatsapp",
    color: "#25D366",
    category: "Messaging",
  },
  {
    id: "signal",
    name: "Signal",
    url: "https://signal.org",
    icon: "message-lock",
    color: "#3A76F0",
    category: "Messaging",
  },

  // ── Video & Media ──
  {
    id: "youtube",
    name: "YouTube",
    url: "https://www.youtube.com",
    icon: "youtube",
    color: "#FF0000",
    category: "Video & Media",
  },
  {
    id: "spotify",
    name: "Spotify",
    url: "https://www.spotify.com",
    icon: "spotify",
    color: "#1DB954",
    category: "Video & Media",
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    url: "https://soundcloud.com",
    icon: "soundcloud",
    color: "#FF5500",
    category: "Video & Media",
  },
  {
    id: "lastfm",
    name: "Last.fm",
    url: "https://www.last.fm",
    icon: "lastfm",
    color: "#D51007",
    category: "Video & Media",
  },
  {
    id: "youtube-music",
    name: "YouTube Music",
    url: "https://music.youtube.com",
    icon: "music",
    color: "#FF0000",
    category: "Video & Media",
  },

  // ── Communication ──
  {
    id: "google-meet",
    name: "Google Meet",
    url: "https://meet.google.com",
    icon: "video",
    color: "#00897B",
    category: "Communication",
  },
  {
    id: "zoom",
    name: "Zoom",
    url: "https://zoom.us",
    icon: "video-outline",
    color: "#0B5CFF",
    category: "Communication",
  },

  // ── Email ──
  {
    id: "gmail",
    name: "Gmail",
    url: "https://mail.google.com",
    icon: "gmail",
    color: "#EA4335",
    category: "Email",
  },
  {
    id: "protonmail",
    name: "Proton Mail",
    url: "https://proton.me",
    icon: "email-lock",
    color: "#6D4AFF",
    category: "Email",
  },
  {
    id: "office365",
    name: "Office 365",
    url: "https://www.office.com",
    icon: "microsoft-office",
    color: "#D83B01",
    category: "Email",
  },

  // ── AI Platforms ──
  {
    id: "claude",
    name: "Claude",
    url: "https://claude.ai",
    icon: "robot",
    color: "#D97757",
    category: "AI Platforms",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    url: "https://chatgpt.com",
    icon: "robot-outline",
    color: "#10A37F",
    category: "AI Platforms",
  },
  {
    id: "gemini",
    name: "Gemini",
    url: "https://gemini.google.com",
    icon: "creation",
    color: "#4285F4",
    category: "AI Platforms",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    url: "https://www.perplexity.ai",
    icon: "magnify",
    color: "#20808D",
    category: "AI Platforms",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    url: "https://www.deepseek.com",
    icon: "brain",
    color: "#4D6BFE",
    category: "AI Platforms",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    url: "https://huggingface.co",
    icon: "emoticon-happy",
    color: "#FFD21E",
    category: "AI Platforms",
  },
  {
    id: "grok",
    name: "Grok",
    url: "https://grok.com",
    icon: "flash",
    color: "#000000",
    category: "AI Platforms",
  },
  {
    id: "mistral",
    name: "Mistral",
    url: "https://mistral.ai",
    icon: "weather-windy",
    color: "#F54E42",
    category: "AI Platforms",
  },

  // ── Hardware / Chips ──
  {
    id: "nvidia",
    name: "NVIDIA",
    url: "https://www.nvidia.com",
    icon: "chip",
    color: "#76B900",
    category: "Hardware",
  },
  {
    id: "amd",
    name: "AMD",
    url: "https://www.amd.com",
    icon: "memory",
    color: "#ED1C24",
    category: "Hardware",
  },
  {
    id: "intel",
    name: "Intel",
    url: "https://www.intel.com",
    icon: "cpu-64-bit",
    color: "#0071C5",
    category: "Hardware",
  },

  // ── Tech Giants ──
  {
    id: "microsoft",
    name: "Microsoft",
    url: "https://www.microsoft.com",
    icon: "microsoft",
    color: "#00A4EF",
    category: "Tech Giants",
  },
  {
    id: "apple",
    name: "Apple",
    url: "https://www.apple.com",
    icon: "apple",
    color: "#A2AAAD",
    category: "Tech Giants",
  },

  // ── Productivity ──
  {
    id: "notion",
    name: "Notion",
    url: "https://www.notion.so",
    icon: "notebook",
    color: "#000000",
    category: "Productivity",
  },
  {
    id: "figma",
    name: "Figma",
    url: "https://www.figma.com",
    icon: "palette",
    color: "#F24E1E",
    category: "Productivity",
  },
  {
    id: "canva",
    name: "Canva",
    url: "https://www.canva.com",
    icon: "brush",
    color: "#00C4CC",
    category: "Productivity",
  },
  {
    id: "capcut",
    name: "CapCut",
    url: "https://www.capcut.com",
    icon: "movie-edit",
    color: "#000000",
    category: "Productivity",
  },
  {
    id: "adobe",
    name: "Adobe",
    url: "https://www.adobe.com",
    icon: "adobe",
    color: "#FF0000",
    category: "Productivity",
  },

  // ── OS & Linux ──
  {
    id: "ubuntu",
    name: "Ubuntu",
    url: "https://ubuntu.com",
    icon: "ubuntu",
    color: "#E95420",
    category: "OS & Linux",
  },
  {
    id: "kali",
    name: "Kali Linux",
    url: "https://www.kali.org",
    icon: "linux",
    color: "#557C94",
    category: "OS & Linux",
  },

  // ── Gaming ──
  {
    id: "steam",
    name: "Steam",
    url: "https://store.steampowered.com",
    icon: "steam",
    color: "#1B2838",
    category: "Gaming",
  },
  {
    id: "epic-games",
    name: "Epic Games",
    url: "https://store.epicgames.com",
    icon: "gamepad-square",
    color: "#313131",
    category: "Gaming",
  },
  {
    id: "playstation",
    name: "PlayStation",
    url: "https://www.playstation.com",
    icon: "sony-playstation",
    color: "#003087",
    category: "Gaming",
  },
  {
    id: "xbox",
    name: "Xbox",
    url: "https://www.xbox.com",
    icon: "microsoft-xbox",
    color: "#107C10",
    category: "Gaming",
  },
  {
    id: "rockstar",
    name: "Rockstar Games",
    url: "https://www.rockstargames.com",
    icon: "star",
    color: "#FCAF17",
    category: "Gaming",
  },
  {
    id: "ea",
    name: "Electronic Arts",
    url: "https://www.ea.com",
    icon: "controller-classic",
    color: "#000000",
    category: "Gaming",
  },

  // ── Speedtest ──
  {
    id: "speedtest",
    name: "Speedtest",
    url: "https://www.speedtest.net",
    icon: "speedometer",
    color: "#141526",
    category: "Network Tools",
  },

  // ── Crypto & Finance ──
  {
    id: "bybit",
    name: "Bybit",
    url: "https://www.bybit.com",
    icon: "bitcoin",
    color: "#F7A600",
    category: "Crypto & Finance",
  },
  {
    id: "metamask",
    name: "MetaMask",
    url: "https://metamask.io",
    icon: "wallet",
    color: "#F6851B",
    category: "Crypto & Finance",
  },
  {
    id: "binance",
    name: "Binance",
    url: "https://www.binance.com",
    icon: "currency-btc",
    color: "#F0B90B",
    category: "Crypto & Finance",
  },

  // ── App Stores ──
  {
    id: "play-store",
    name: "Play Store",
    url: "https://play.google.com",
    icon: "google-play",
    color: "#414141",
    category: "App Stores",
  },

  // ── PC Manufacturers ──
  {
    id: "asus",
    name: "ASUS",
    url: "https://www.asus.com",
    icon: "laptop",
    color: "#00539B",
    category: "PC Manufacturers",
  },
  {
    id: "acer",
    name: "Acer",
    url: "https://www.acer.com",
    icon: "monitor",
    color: "#83B81A",
    category: "PC Manufacturers",
  },
  {
    id: "lenovo",
    name: "Lenovo",
    url: "https://www.lenovo.com",
    icon: "laptop",
    color: "#E2231A",
    category: "PC Manufacturers",
  },
  {
    id: "msi",
    name: "MSI",
    url: "https://www.msi.com",
    icon: "desktop-tower-monitor",
    color: "#FF0000",
    category: "PC Manufacturers",
  },
  {
    id: "gigabyte",
    name: "Gigabyte",
    url: "https://www.gigabyte.com",
    icon: "expansion-card",
    color: "#1E4FBB",
    category: "PC Manufacturers",
  },
];

export const CATALOG_CATEGORIES = [
  ...new Set(RESOURCE_CATALOG.map((r) => r.category)),
];

export const DEFAULT_ENABLED_IDS = [
  "google",
  "cloudflare",
  "aws",
  "github",
  "gitlab",
  "microsoft",
  "apple",
  "vercel",
  "digitalocean",
  "ibm",
  "facebook",
];
