import type { Resource } from '../types';

export const DEFAULT_RESOURCES: Resource[] = [
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    url: 'https://www.cloudflare.com',
    icon: 'cloud',
    color: '#F6821F',
    isBuiltIn: true,
    category: 'CDN / DNS',
    history: [],
  },
  {
    id: 'google',
    name: 'Google',
    url: 'https://www.google.com',
    icon: 'google',
    color: '#4285F4',
    isBuiltIn: true,
    category: 'Search / Cloud',
    history: [],
  },
  {
    id: 'meta',
    name: 'Meta',
    url: 'https://www.meta.com',
    icon: 'facebook',
    color: '#0668E1',
    isBuiltIn: true,
    category: 'Social',
    history: [],
  },
  {
    id: 'aws',
    name: 'AWS',
    url: 'https://aws.amazon.com',
    icon: 'aws',
    color: '#FF9900',
    isBuiltIn: true,
    category: 'Cloud',
    history: [],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    url: 'https://vercel.com',
    icon: 'triangle',
    color: '#000000',
    isBuiltIn: true,
    category: 'Hosting',
    history: [],
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    url: 'https://www.microsoft.com',
    icon: 'microsoft',
    color: '#00A4EF',
    isBuiltIn: true,
    category: 'Cloud / Software',
    history: [],
  },
  {
    id: 'apple',
    name: 'Apple',
    url: 'https://www.apple.com',
    icon: 'apple',
    color: '#A2AAAD',
    isBuiltIn: true,
    category: 'Hardware / Services',
    history: [],
  },
  {
    id: 'digitalocean',
    name: 'DigitalOcean',
    url: 'https://www.digitalocean.com',
    icon: 'water',
    color: '#0080FF',
    isBuiltIn: true,
    category: 'Cloud',
    history: [],
  },
  {
    id: 'ibm',
    name: 'IBM',
    url: 'https://www.ibm.com',
    icon: 'server',
    color: '#0F62FE',
    isBuiltIn: true,
    category: 'Cloud / Enterprise',
    history: [],
  },
  {
    id: 'github',
    name: 'GitHub',
    url: 'https://github.com',
    icon: 'github',
    color: '#24292F',
    isBuiltIn: true,
    category: 'Dev Tools',
    history: [],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    url: 'https://gitlab.com',
    icon: 'git',
    color: '#FC6D26',
    isBuiltIn: true,
    category: 'Dev Tools',
    history: [],
  },
];

export const DEFAULT_SETTINGS = {
  refreshInterval: 30000,
  autoRefresh: true,
  theme: "system" as const,
  timeout: 10000,
  maxHistoryItems: 50,
  notificationsEnabled: true,
  backgroundCheckEnabled: false,
  hapticFeedback: true,
};
