plugins {
    id 'com.android.application'
}

android {
    namespace 'com.netprobe'
    compileSdk 36

    defaultConfig {
        applicationId "com.netprobe"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('../netprobe.keystore')
            storePassword 'DXBAKZFQNIEIOAAAAAAAAAAAAA'
            keyAlias 'netprobe'
            keyPassword 'DXBAKZFQNIEIOAAAAAAAAAAAAA'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
